remote_mode: false
online_mode: false
perf_name: throughput
perf_unit: eps
vacuum_full: True

benchmark: sysbench
sysbench_mode: read_write_test_ratio_13

# saved locally
knob_definitions: postgres_110.json
knob_num: -1

negate: false