seed: 11126
batch_size: 1
init_design: lhs

optimizer: mcts-winter
optimizer_params:
  save_path: True
  save_tr: True
  leaf_size: 10

  global_num_init: 20
  local_num_init: 10
  local_init_design: sobol

  local_control_params:
    real_mode: True
  local_optimizer_type: turbo
  local_optimizer_params:
    turbo_state_params:
      failure_tolerance: 5
      success_tolerance: 3
      length_min: '0.5**5'
