
seed: 11126
batch_size: 1
init_design: lhs

optimizer: turbo
optimizer_params:
  num_init: 20
  save_tr: True
  acqf: 'ts'
  turbo_state_params: 
    failure_tolerance: 5
    success_tolerance: 3
    length_min: '0.5**5'