
seed: 11126
batch_size: 1
init_design: lhs
  
optimizer: turbo
optimizer_params:
  save_tr: True
  num_init: 2
  acqf: 'ts'
  use_copilot: True
  copilot_params:
    success_tolerance: 5
    failure_tolerance: 3
    tree_params:
      temperature: 0.3
      classifier_cls: 'base'
      classifier_type: 'svm'
      adapt_Cp: True
      cluter_score_threshold: 0.1
  turbo_state_params:
    success_tolerance: 3
    failure_tolerance: 5
    length_min: '0.5**5'