seed: 11126
batch_size: 4
init_design: lhs

optimizer: mcts-ref
optimizer_params:
  global_num_init: 20
  local_num_init: 20
  leaf_size: 20
  classifier_params:
    kernel_type: 'rbf'
    gamma_type: 'auto'
  local_optimizer_type: turbo