seed: 11126
num_evals: 1000
batch_size: 4
init_design: lhs
  
optimizer: turbo
optimizer_params:
  num_init: 20
  acqf: 'ts'
  n_candidates: 3000
  save_tr: True
  
  use_copilot: True
  copilot_params:
    failure_tolerance: 3
    success_tolerance: 5
    tree_params:
      temperature: 0.3
      gen_cands: True
      gen_batch: False
      classifier_cls: 'base'
      classifier_type: 'svm'
      cluter_score_threshold: 0.2
  turbo_state_params:
    failure_tolerance: 5
    success_tolerance: 3
    length_min: "0.5**7"