seed: 11126
num_evals: 1000
batch_size: 4
init_design: sobol
  
optimizer: turbo
optimizer_params:
  num_init: 20
  acqf: 'ts'
  copilot_type: II
  copilot_params:
    node_selection_type: 'ucb'
    tree_params:
      classifier_type: 'svm'
  turbo_state_params:
    failure_tolerance: 5
    success_tolerance: 3
    length_min: "0.5**7"