seed: 11126
num_evals: 1000
batch_size: 4
init_design: lhs
  
optimizer: turbo
optimizer_params:
  num_init: 40
  acqf: 'ts'
  fix_sobol: True

  use_copilot: True
  copilot_params:
    tree_params:
      temperature: 0.3
      adapt_Cp: True
      classifier_cls: 'base'
      classifier_type: 'svm'
      cluter_score_threshold: 0.1
  turbo_state_params:
    failure_tolerance: 5
    success_tolerance: 3
    length_min: "0.5**7"