seed: 11126
num_evals: 1000
batch_size: 4
init_design: lhs
  
optimizer: turbo
optimizer_params:
  num_init: 20
  acqf: 'ts'
  copilot_type: V
  copilot_params:
    tree_params:
      temperature: 0.1
      classifier_cls: 'base'
      classifier_type: 'svm'
      cluter_score_threshold: 0.1
      classifier_params:
        kernel: 'poly'
  turbo_state_params:
    failure_tolerance: 5
    success_tolerance: 3
    length_min: "0.5**7"