seed: 11126
num_evals: 1000
batch_size: 4
init_design: sobol
  
optimizer: turbo
optimizer_params:
  num_init: 20
  acqf: 'ts'
  use_copilot: True
  copilot_params:
    tree_params:
      cluster_type: dbscan
  turbo_state_params:
      failure_tolerance: 5
      success_tolerance: 3
      length_min: "0.5**7"