seed: 11126
num_evals: 1000
batch_size: 4
init_design: lhs
  
optimizer: turbo
optimizer_params:
  num_init: 20
  acqf: 'ts'
  use_copilot: True
  copilot_params:
    failure_tolerance: 3
    success_tolerance: 5
    tree_params:
      node_selection_type: 'Mean'
      classifier_cls: 'base'
      classifier_type: 'svm'
      cluter_score_threshold: 0.1
  turbo_state_params:
    failure_tolerance: 5
    success_tolerance: 3
    length_min: "0.5**7"